
import { connectDb, getDatabase, closeConnectionDb } from '../mongoConnection';

export const initialProducts = [
  {
    name: 'Boieesen Art - Cuadro de pintura al óleo con textura pintada a mano (29.9 x 39.4 x 39.4 in), diseño abstracto moderno y rojo',
	code: 'B091HP6RY0',
	brand: 'XIN',
	price: 39.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Marrón (Brown Elephant)"],
	material: "Aceite",
	theme: "Rustic",
	productWeight: 1.5,
	weightUnit: "pounds",
	productLength: 29,
	lengthUnit: "pulgadas",
	ProductWidth: 2.87,
	ProductHeight:  20.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81M5RO9iTML._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/91VR1webwNL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/91DoMq3B4QL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/816+34-pMTL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51I7FLaIPuL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/41fj4Mi1oRL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/41xHGW9Z6RL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/31gKmVVP64L._AC_US40_.jpg"
  },
  {
    name: 'Yelash Lienzo decorativo para pared con diseño de pavo real con plumas verticales coloridas sobre ramas de flores blancas',
	code: 'B091HP6RY1',
	brand: 'Yelash',
	price: 59.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "Ideas de diseño: pareja elegante pavo real enamorado. Peacock es un pájaro auspicioso en la mitología, tiene un aspecto hermoso y un estilo noble y rey. Esta imagen inspiradora y motivadora hace que sea un acento ideal para cualquier habitación de la casa.",
	category: "Oil",
	colors: ["Pareja Peacock"],
	material: "Lona",
	theme: "Animal",
	productWeight: 2,
	weightUnit: "pounds",
	productLength: 24,
	lengthUnit: "pulgadas",
	ProductWidth: 1,
	ProductHeight:  36,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81s4pGH2kOL._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/819yD6BWecL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/91T-VKaIFZL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81J2pf+PmHL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51y7I76l5WL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51r-NTif1GL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/61zwFUn2ivL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/513FyZN0mDL._AC_US40_.jpg"
  },
  {
    name: "YaSheng Art - Pintura al óleo pintada a mano sobre lienzo con flores blancas, pintura moderna para decoración interior",
	code: 'B091HP6RYY2',
	brand: 'Winpeak Art',
	price: 79.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "Pintura al óleo sobre lienzo 100% hecha a mano por nuestros artistas profesionales. Este arte mural abstracto es adecuado para sala de estar, dormitorio, cocina, oficina, hotel, comedor, baño, bar, etc.",
	category: "Oil",
	colors: ["Pkt016"],
	material: "Aceite",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 48,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/710TdMSGpxL._AC_SL1200_.jpg",
	image1: "https://m.media-amazon.com/images/I/71OgJYbJ-zL._AC_SL1200_.jpg",
	image2: "https://m.media-amazon.com/images/I/71Cr4Ch8eQL._AC_SL1200_.jpg",
	image3: "https://m.media-amazon.com/images/I/71dgYUQtvDL._AC_SL1200_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51GJ6WmOnPL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/515QgmyfoEL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/510U03O6myL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51IEuATff2L._AC_US40_.jpg"
  },
  {
    name: "Pintura al óleo, pintada a mano sobre lienzo, paisaje de lago, arte abstracto para pared, moderno, decoración del hogar.",
	code: 'B091HP6RYY3',
	brand: 'ULIANUAN',
	price: 99.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "Artesanía: 100% pintado a mano por artistas profesionales experimentados. Estirado y enmarcado que están equipados con ganchos negros para colgar e instalar fácilmente.",
	category: "Oil",
	colors: ["Cl04"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 5.74,
	weightUnit: "pounds",
	productLength: 48,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81PZ20ss0KL._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81tT1MOy8TL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/81Gd0RvKUUL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/71KlUisU0NL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51tCKkeu40L._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/61Kv7JfssvL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/514+SsRkAiL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51LWcsMhZSL._AC_US40_.jpg"
  },
  {
    name: 'Pinturas al óleo pintadas a mano sobre lienzo, lienzo de velero, pintura abstracta de paisaje marino, ',
	code: 'Diathou',
	brand: 'Yelash',
	price: 109.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "Esta obra de arte está pintada a mano por nuestros artistas profesionales. Este lienzo hecho a mano es adecuado para sala de estar, dormitorio, cocina, oficina, hotel, comedor, baño, pasillo, bar, etc. y otros espacios para los amantes del arte.",
	category: "Oil",
	colors: ["M012"],
	material: "Lona",
	theme: "Landscape",
	productWeight: 5.65,
	weightUnit: "pounds",
	productLength: 47.2,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  23.6,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/91dCsZ4tV2L._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81iH3ZnyCUL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/918TWtZmyxL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81KbcLFHJxL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/5144gNEnNYL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51jmPrjmIWL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/51u1Nye4VVL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/510yCXFEjQL._AC_US40_.jpg"
  },
  {
    name: 'AMEI Pinturas de arte, 24.0 x 44.1 in, 3D pintado a mano sobre lienzo colorido fondo blanco abstracto pinturas ',
	code: 'B091HP6RYY5',
	brand: 'Diathou',
	price: 49.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81s4pGH2kOL._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/819yD6BWecL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/91T-VKaIFZL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81J2pf+PmHL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51y7I76l5WL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51r-NTif1GL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/61zwFUn2ivL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/513FyZN0mDL._AC_US40_.jpg"
  },
  {
    name: 'V-inspire - Pinturas abstractas abstractas de 24.0 x 47.6 in, pintura abstracta en 3D moderna con textura roja ',
	code: 'B091HP6RYY6',
	brand: 'Diathou',
	price: 19.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/710TdMSGpxL._AC_SL1200_.jpg",
	image1: "https://m.media-amazon.com/images/I/71OgJYbJ-zL._AC_SL1200_.jpg",
	image2: "https://m.media-amazon.com/images/I/71Cr4Ch8eQL._AC_SL1200_.jpg",
	image3: "https://m.media-amazon.com/images/I/71dgYUQtvDL._AC_SL1200_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51GJ6WmOnPL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/515QgmyfoEL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/510U03O6myL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51IEuATff2L._AC_US40_.jpg"
  },
  {
    name: 'YaSheng Arte, cuadro contempor&aacute;neo pintado a mano, motivo de flores blancas',
	code: 'B091HP6RYY7',
	brand: 'Diathou',
	price: 149.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81PZ20ss0KL._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81tT1MOy8TL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/81Gd0RvKUUL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/71KlUisU0NL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51tCKkeu40L._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/61Kv7JfssvL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/514+SsRkAiL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51LWcsMhZSL._AC_US40_.jpg"
  },
  {
    name: 'SD Soft Dance - Pintura al óleo enmarcada en lienzo costero - Pintada a mano con arte de pared texturizado para sala',
	code: 'B091HP6RYY8',
	brand: 'Winpeak Art',
	price: 29.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/91dCsZ4tV2L._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81iH3ZnyCUL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/918TWtZmyxL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81KbcLFHJxL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/5144gNEnNYL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51jmPrjmIWL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/51u1Nye4VVL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/510yCXFEjQL._AC_US40_.jpg"
  },
  {
    name: 'Pintura tradicional china pintada a mano de ciruelo en flor de ciruelo arte de pared moderno en blanco y negro paisaje',
	code: 'B091HP6RYY9',
	brand: 'Winpeak Art',
	price: 89.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/91dCsZ4tV2L._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81iH3ZnyCUL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/918TWtZmyxL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81KbcLFHJxL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/5144gNEnNYL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51jmPrjmIWL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/51u1Nye4VVL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/510yCXFEjQL._AC_US40_.jpg"
  },
  {
    name: 'YHSKY ARTS Lienzo abstracto hecho a mano, pinturas al óleo modernas azules y doradas, imágenes grandes',
	code: 'B091HP6RYY10',
	brand: 'Yelash',
	price: 29.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81s4pGH2kOL._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/819yD6BWecL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/91T-VKaIFZL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81J2pf+PmHL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51y7I76l5WL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51r-NTif1GL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/61zwFUn2ivL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/513FyZN0mDL._AC_US40_.jpg"
  },
  {
    name: 'Diathou Pintado a mano tela acrílica enmarcada arte de la pared pintura al óleo, paisaje urbano arte pintura,',
	code: 'B091HP6RYY11',
	brand: 'Winpeak Art',
	price: 49.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/710TdMSGpxL._AC_SL1200_.jpg",
	image1: "https://m.media-amazon.com/images/I/71OgJYbJ-zL._AC_SL1200_.jpg",
	image2: "https://m.media-amazon.com/images/I/71Cr4Ch8eQL._AC_SL1200_.jpg",
	image3: "https://m.media-amazon.com/images/I/71dgYUQtvDL._AC_SL1200_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51GJ6WmOnPL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/515QgmyfoEL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/510U03O6myL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51IEuATff2L._AC_US40_.jpg"
  },
  {
    name: 'Pinturas al óleo Van Gogh el Café Terraza en la Place Du Forum Reproducción Pinturas al óleo pintadas a mano',
	code: 'B091HP6RYY12',
	brand: 'Winpeak Art',
	price: 69.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81PZ20ss0KL._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81tT1MOy8TL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/81Gd0RvKUUL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/71KlUisU0NL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51tCKkeu40L._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/61Kv7JfssvL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/514+SsRkAiL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51LWcsMhZSL._AC_US40_.jpg"
  },
  {
    name: 'AMATOP Arte para pared, flor enmarcada pintada a mano, pintura al óleo sobre lienzo, galería, obra de arte floral',
	code: 'B091HP6RYY13',
	brand: 'XIN',
	price: 9.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/91dCsZ4tV2L._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81iH3ZnyCUL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/918TWtZmyxL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81KbcLFHJxL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/5144gNEnNYL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51jmPrjmIWL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/51u1Nye4VVL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/510yCXFEjQL._AC_US40_.jpg"
  },
  {
    name: 'Zlove - Cuadro decorativo para pared, diseño de abedul, color blanco',
	code: 'B091HP6RYY14',
	brand: 'Yelash',
	price: 69.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["M012"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/91dCsZ4tV2L._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81iH3ZnyCUL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/918TWtZmyxL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81KbcLFHJxL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/5144gNEnNYL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51jmPrjmIWL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/51u1Nye4VVL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/510yCXFEjQL._AC_US40_.jpg"
  },
  {
    name: 'V-inspire Art Art - Lienzo decorativo para pared de 24 x 48 pulgadas, pintura al óleo, sala de estar, dormitorio, pinturas',
	code: 'B091HP6RYY15',
	brand: 'XIN',
	price: 249.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Amarillo", "azul", "blanco"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81s4pGH2kOL._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/819yD6BWecL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/91T-VKaIFZL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81J2pf+PmHL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51y7I76l5WL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51r-NTif1GL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/61zwFUn2ivL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/513FyZN0mDL._AC_US40_.jpg"
  },
  {
    name: 'Yotree Pinturas al óleo, 24.0 x 47.6 in, 3D sobre lienzo paisaje de río en otoño abstracto arte de pared con vista de la ciudad',
	code: 'B091HP6RYY16',
	brand: 'ULIANUAN',
	price: 129.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Mediterranean"],
	material: "Madera",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/710TdMSGpxL._AC_SL1200_.jpg",
	image1: "https://m.media-amazon.com/images/I/71OgJYbJ-zL._AC_SL1200_.jpg",
	image2: "https://m.media-amazon.com/images/I/71Cr4Ch8eQL._AC_SL1200_.jpg",
	image3: "https://m.media-amazon.com/images/I/71dgYUQtvDL._AC_SL1200_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51GJ6WmOnPL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/515QgmyfoEL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/510U03O6myL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51IEuATff2L._AC_US40_.jpg"
  },
  {
    name: '5 pinturas de pavo real en el bosque 3D pintadas a mano, pintura al óleo, pintura de animales, estilo chino clásico',
	code: 'B091HP6RYY17',
	brand: 'ULIANUAN',
	price: 109.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Azul / Patchwork"],
	material: "Aceite",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81PZ20ss0KL._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81tT1MOy8TL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/81Gd0RvKUUL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/71KlUisU0NL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51tCKkeu40L._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/61Kv7JfssvL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/514+SsRkAiL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51LWcsMhZSL._AC_US40_.jpg"
  },
  {
    name: 'Yelash Lienzo decorativo para pared con diseño de pavo real con plumas verticales coloridas sobre ramas de flores blancas',
	code: 'B091HP6RYY18',
	brand: 'ULIANUAN',
	price: 39.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Negro"],
	material: "Lona",
	theme: "Vintage",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/91dCsZ4tV2L._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81iH3ZnyCUL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/918TWtZmyxL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81KbcLFHJxL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/5144gNEnNYL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51jmPrjmIWL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/51u1Nye4VVL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/510yCXFEjQL._AC_US40_.jpg"
  },
  {
    name: 'V-inspire Art,24.0 x 47.6 in moderno abstracto pintado a mano lienzo acrílico pintura al óleo árbol arte lienzo arte ',
	code: 'B091HP6RYY19',
	brand: 'ULIANUAN',
	price: 49.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Aurora"],
	material: "Lona",
	theme: "Modern",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/91dCsZ4tV2L._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81iH3ZnyCUL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/918TWtZmyxL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81KbcLFHJxL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/5144gNEnNYL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51jmPrjmIWL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/51u1Nye4VVL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/510yCXFEjQL._AC_US40_.jpg"
  },
  {
    name: 'AZAVY Art,24.0 x 44.1 in, 100 % pintado a mano, obra de arte moderna con textura de lluvia de meteoros, pinturas al óleo',
	code: 'B091HP6RYY20',
	brand: 'XIN',
	price: 89.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81s4pGH2kOL._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/819yD6BWecL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/91T-VKaIFZL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81J2pf+PmHL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51y7I76l5WL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51r-NTif1GL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/61zwFUn2ivL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/513FyZN0mDL._AC_US40_.jpg"
  },
  {
    name: 'Pintura al óleo sobre lienzo pintada a mano, diseño de reflejo de paisaje urbano moderno',
	code: 'B091HP6RYY21',
	brand: 'Yelash',
	price: 169.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/710TdMSGpxL._AC_SL1200_.jpg",
	image1: "https://m.media-amazon.com/images/I/71OgJYbJ-zL._AC_SL1200_.jpg",
	image2: "https://m.media-amazon.com/images/I/71Cr4Ch8eQL._AC_SL1200_.jpg",
	image3: "https://m.media-amazon.com/images/I/71dgYUQtvDL._AC_SL1200_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51GJ6WmOnPL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/515QgmyfoEL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/510U03O6myL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51IEuATff2L._AC_US40_.jpg"
  },
  {
    name: 'Amei Pinturas de arte, 24.0 x 47.6 in pintado a mano con textura de pared sobre lienzo Pintura al óleo a mano',
	code: 'B091HP6RYY22',
	brand: 'XIN',
	price: 59.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81PZ20ss0KL._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81tT1MOy8TL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/81Gd0RvKUUL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/71KlUisU0NL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51tCKkeu40L._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/61Kv7JfssvL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/514+SsRkAiL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51LWcsMhZSL._AC_US40_.jpg"
  },
  {
    name: 'V-inspire Art,24.0 x 47.6 in moderno abstracto 3D pintado a mano pinturas al óleo lienzo pintado acrílico decoración',
	code: 'B091HP6RYY23',
	brand: 'COPR',
	price: 79.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Azul"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/91dCsZ4tV2L._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81iH3ZnyCUL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/918TWtZmyxL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81KbcLFHJxL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/5144gNEnNYL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51jmPrjmIWL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/51u1Nye4VVL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/510yCXFEjQL._AC_US40_.jpg"
  },
  {
    name: 'V-inspire Arte abstracto moderno de 24 x 48 pulgadas, pintura al óleo pintada a mano sobre lienzo, arte abstracto',
	code: 'B091HP6RYY24',
	brand: 'COPR',
	price: 69.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Multicolor"],
	material: "Plástico",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/91dCsZ4tV2L._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81iH3ZnyCUL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/918TWtZmyxL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81KbcLFHJxL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/5144gNEnNYL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51jmPrjmIWL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/51u1Nye4VVL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/510yCXFEjQL._AC_US40_.jpg"
  },
  {
    name: 'YaSheng Art - Pintura al óleo sobre lienzo con textura colorida escena nocturna abstracta de arte contemporáneo',
	code: 'B091HP6RYY25',
	brand: 'XIN',
	price: 29.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Abstracto"],
	material: "Canvas",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81s4pGH2kOL._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/819yD6BWecL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/91T-VKaIFZL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81J2pf+PmHL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51y7I76l5WL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51r-NTif1GL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/61zwFUn2ivL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/513FyZN0mDL._AC_US40_.jpg"
  },
  {
    name: 'Orlco Art Modern pintura abstracta al &oacute;leo, pintada a mano, dorado, gris, blanco',
	code: 'B091HP6RYY26',
	brand: 'XIN',
	price: 49.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Verde azulado"],
	material: "Aceite",
	theme: "Floral",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/710TdMSGpxL._AC_SL1200_.jpg",
	image1: "https://m.media-amazon.com/images/I/71OgJYbJ-zL._AC_SL1200_.jpg",
	image2: "https://m.media-amazon.com/images/I/71Cr4Ch8eQL._AC_SL1200_.jpg",
	image3: "https://m.media-amazon.com/images/I/71dgYUQtvDL._AC_SL1200_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51GJ6WmOnPL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/515QgmyfoEL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/510U03O6myL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51IEuATff2L._AC_US40_.jpg"
  },
  {
    name: 'Bayland Collection - Pintura al óleo abstracta (24.0 x 47.6 in, 100 % pintado a mano, pintura al óleo pintada a mano',
	code: 'B091HP6RYY27',
	brand: 'COPR',
	price: 139.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Café romántico"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81PZ20ss0KL._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81tT1MOy8TL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/81Gd0RvKUUL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/71KlUisU0NL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51tCKkeu40L._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/61Kv7JfssvL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/514+SsRkAiL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51LWcsMhZSL._AC_US40_.jpg"
  },
  {
    name: 'Paimuni Lienzo pintado a mano, 100 % de Italia Town Mediterránea de la costa del mar de Toscana con flores al óleo',
	code: 'B091HP6RYY28',
	brand: 'COPR',
	price: 59.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/91dCsZ4tV2L._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81iH3ZnyCUL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/918TWtZmyxL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81KbcLFHJxL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/5144gNEnNYL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51jmPrjmIWL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/51u1Nye4VVL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/510yCXFEjQL._AC_US40_.jpg"
  },
  {
    name: 'Pintura abstracta moderna decoración urbana arte de la pared de la lona enmarcada de la pintura del arte de la pared',
	code: 'B091HP6RYY29',
	brand: 'XIN',
	price: 39.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/91dCsZ4tV2L._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81iH3ZnyCUL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/918TWtZmyxL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81KbcLFHJxL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/5144gNEnNYL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51jmPrjmIWL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/51u1Nye4VVL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/510yCXFEjQL._AC_US40_.jpg"
  },
  {
    name: 'Cuadro abstracto lienzo arte de la pared: decoración moderna pintura enmarcada para salas de estar (24 x 36 pulgadas, AB3)',
	code: 'B091HP6RYY30',
	brand: 'COPR',
	price: 99.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81s4pGH2kOL._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/819yD6BWecL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/91T-VKaIFZL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/81J2pf+PmHL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51y7I76l5WL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51r-NTif1GL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/61zwFUn2ivL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/513FyZN0mDL._AC_US40_.jpg"
  },
  {
    name: 'Cuadro abstracto lienzo arte de la pared: decoración moderna pintura enmarcada para salas de estar ',
	code: 'B091HP6RYY31',
	brand: 'XIN',
	price: 69.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/710TdMSGpxL._AC_SL1200_.jpg",
	image1: "https://m.media-amazon.com/images/I/71OgJYbJ-zL._AC_SL1200_.jpg",
	image2: "https://m.media-amazon.com/images/I/71Cr4Ch8eQL._AC_SL1200_.jpg",
	image3: "https://m.media-amazon.com/images/I/71dgYUQtvDL._AC_SL1200_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51GJ6WmOnPL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/515QgmyfoEL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/510U03O6myL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51IEuATff2L._AC_US40_.jpg"
  },
  {
    name: 'Wieco Art Modern Contemporary Flowers Framed Artwork 3 Panels 100% Hand Painted Abstract Floral Oil Paintings',
	code: 'B091HP6RYY32',
	brand: 'XIN',
	price: 79.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/81PZ20ss0KL._AC_SL1500_.jpg",
	image1: "https://m.media-amazon.com/images/I/81tT1MOy8TL._AC_SL1500_.jpg",
	image2: "https://m.media-amazon.com/images/I/81Gd0RvKUUL._AC_SL1500_.jpg",
	image3: "https://m.media-amazon.com/images/I/71KlUisU0NL._AC_SL1500_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51tCKkeu40L._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/61Kv7JfssvL._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/514+SsRkAiL._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51LWcsMhZSL._AC_US40_.jpg"
  },
  {
    name: 'Lienzo abstracto con impresiones al óleo, tamaño grande, 35.8 x 24.0 in, arte abstracto, obra de arte moderno',
	code: 'B091HP6RYY33',
	brand: 'COPR',
	price: 29.99,
	currency: 'USD',
	productBullets: ["obra de arte","pintura al óleo","pintura abstracta","alta definición ","lienzo ecológico ","no se decolora","antiultravioleta", "impermeable"],
	productDescription: "una obra de arte bien seleccionada puede ser el punto focal de tu espacio, pinturas al óleo abstractas que cuentan una historia sobre ti e inspiran conversación, motivación y creatividad. Nuestras modernas pinturas abstractas al óleo son meticulosamente curadas y creadas por varios artistas de todo el mundo, proporcionando diversas opciones para cada estilo de decoración y personalidad.",
	category: "Oil",
	colors: ["Círculo"],
	material: "Lona",
	theme: "Abstract",
	productWeight: 4.29,
	weightUnit: "pounds",
	productLength: 36.1,
	lengthUnit: "pulgadas",
	ProductWidth: 2,
	ProductHeight:  24.5,
	stock: 100,
	imageMain: "https://m.media-amazon.com/images/I/710IvsAuYnL._AC_SL1200_.jpg",
	image1: "https://m.media-amazon.com/images/I/61sxCIh6KLS._AC_SL1200_.jpg",
	image2: "https://m.media-amazon.com/images/I/714eH135hOS._AC_SL1200_.jpg",
	image3: "https://m.media-amazon.com/images/I/71KaafJcmtS._AC_SL1200_.jpg",
	imageMainMini: "https://m.media-amazon.com/images/I/51sPU0hSCtL._AC_US40_.jpg",
	image1Mini: "https://m.media-amazon.com/images/I/51LfjS8mH7S._AC_US40_.jpg",
	image2Mini: "https://m.media-amazon.com/images/I/51rRKk1qlUS._AC_US40_.jpg",
	image3Mini: "https://m.media-amazon.com/images/I/51tlhR5vuaS._AC_US40_.jpg"
  } 
];


const populate = async () => {
	await connectDb();	
	const database =  getDatabase();
	const products = database.collection("products");
	await products.deleteMany({});

	for(const product of initialProducts){	
		await products.insertOne(product);
	}

	await closeConnectionDb();

};

populate().then(() => {
    console.log("end of all");
}).catch(err => {
    console.log(err);
});

